services:
  # Node.js app service
  server:
    build:
      context: .
    env_file:
      - .env-dev
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    command: npm run start:dev

  # MySQL database service
  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    env_file:
      - .env-dev
    volumes:
      - db-data:/var/lib/mysql
      - ./sql-scripts:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  db-data:
